
import java.awt.Dimension;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gabriel
 */
public class AjoutLotDlg extends javax.swing.JDialog {

    private boolean ok;
    private PanneauImage pi;
    private Lot lot;
    JComboBox combobox;

    public boolean getOk() {
        return ok;
    }
    
    public AjoutLotDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ajouteComboBox();
        BBon.setSelected(true);
        ok = false;
        BNiveau1.setSelected(true);
        this.lot = new Lot();
        this.lot.setNiveau(1);
        setTitle("Ajout d'un lot");
    }

    public Lot getLot() {
        return lot;
    }
    
    private void ajouteComboBox()
    {
        combobox = new JComboBox();
        combobox.addItem("30 euros");
        combobox.addItem("50 euros");
        combobox.addItem("90 euros");
        jPanel7.add(combobox);
    }
    
    private void boutonActionPerformed(java.awt.event.ActionEvent evt)
    {
        JFileChooser choix = new JFileChooser();
        choix.showOpenDialog(this);
        String path=choix.getSelectedFile().getAbsolutePath();
        pi = new PanneauImage();
        jPanel2.add(pi);
        pi.setImage(new ImageIcon(path).getImage());
        pack();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PCentre = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Descriptif = new javax.swing.JTextPane();
        jPanel5 = new javax.swing.JPanel();
        BCadeau = new javax.swing.JRadioButton();
        BBon = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        BNiveau1 = new javax.swing.JRadioButton();
        BNiveau2 = new javax.swing.JRadioButton();
        BNiveau3 = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        Annuler = new javax.swing.JButton();
        Valider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Saisie d'un nouveau lot");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        PCentre.setLayout(new java.awt.GridLayout(1, 2));

        jPanel2.setLayout(new java.awt.GridLayout(5, 1));

        jLabel2.setText("Descriptif");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel2.add(jPanel8);

        jLabel3.setText("Catégorie");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel2.add(jPanel9);

        jLabel4.setText("Niveau");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel2.add(jPanel10);

        PCentre.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(5, 1));

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane2.setViewportView(Descriptif);

        jPanel4.add(jScrollPane2);

        jPanel3.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        buttonGroup1.add(BCadeau);
        BCadeau.setText("Cadeau");
        BCadeau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCadeauActionPerformed(evt);
            }
        });
        jPanel5.add(BCadeau);

        buttonGroup1.add(BBon);
        BBon.setText("Bon");
        BBon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBonActionPerformed(evt);
            }
        });
        jPanel5.add(BBon);

        jPanel3.add(jPanel5);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        buttonGroup2.add(BNiveau1);
        BNiveau1.setText("1");
        BNiveau1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNiveau1ActionPerformed(evt);
            }
        });
        jPanel6.add(BNiveau1);

        buttonGroup2.add(BNiveau2);
        BNiveau2.setText("2");
        BNiveau2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNiveau2ActionPerformed(evt);
            }
        });
        jPanel6.add(BNiveau2);

        buttonGroup2.add(BNiveau3);
        BNiveau3.setText("3");
        BNiveau3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNiveau3ActionPerformed(evt);
            }
        });
        jPanel6.add(BNiveau3);

        jPanel3.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));
        jPanel3.add(jPanel7);

        PCentre.add(jPanel3);

        getContentPane().add(PCentre, java.awt.BorderLayout.CENTER);

        jPanel11.setLayout(new java.awt.GridLayout(1, 2));

        Annuler.setText("Annuler");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        jPanel11.add(Annuler);

        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });
        jPanel11.add(Valider);

        getContentPane().add(jPanel11, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BCadeauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCadeauActionPerformed
    jPanel7.removeAll();
    JButton bouton = new JButton("Parcourir");
    bouton.addActionListener(new ActionListener()
            {
                public void actionPerformed(ActionEvent evt)
                {
                    boutonActionPerformed(evt); 
                }
            });
    bouton.setPreferredSize(new Dimension(30,30));
    bouton.setVisible(true);
    bouton.setEnabled(true);
    jPanel7.add(bouton);
    jPanel7.repaint();
    pack();
    }//GEN-LAST:event_BCadeauActionPerformed

    private void BNiveau1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNiveau1ActionPerformed
      this.lot.setNiveau(1);
    }//GEN-LAST:event_BNiveau1ActionPerformed

    private void BNiveau2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNiveau2ActionPerformed
       this.lot.setNiveau(2);
    }//GEN-LAST:event_BNiveau2ActionPerformed

    private void BBonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBonActionPerformed
    jPanel7.removeAll();
    pi.setImage(null);
    ajouteComboBox();
    jPanel7.repaint();
    pack();
    }//GEN-LAST:event_BBonActionPerformed

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
     this.setVisible(false);
     this.dispose();
    }//GEN-LAST:event_AnnulerActionPerformed

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        ok = true;
        this.lot.setDescription(Descriptif.getText());
        if(BBon.isSelected()&&combobox.getSelectedIndex()==0)
        {
              this.lot.setDescription(Descriptif.getText()+" d'une valeur de 30€");  
        }
        if(BBon.isSelected()&&combobox.getSelectedIndex()==1)
        {
            this.lot.setDescription(Descriptif.getText()+" d'une valeur de 50€");
        }
        if(BBon.isSelected()&&combobox.getSelectedIndex()==2)
        {
            this.lot.setDescription(Descriptif.getText()+" d'une valeur de 90€");
        }
        if(BCadeau.isSelected())
        {
            this.lot.setImage(pi.getImage());
        }
        
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_ValiderActionPerformed

    private void BNiveau3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNiveau3ActionPerformed
       this.lot.setNiveau(3);
    }//GEN-LAST:event_BNiveau3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutLotDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutLotDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutLotDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutLotDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AjoutLotDlg dialog = new AjoutLotDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JRadioButton BBon;
    private javax.swing.JRadioButton BCadeau;
    private javax.swing.JRadioButton BNiveau1;
    private javax.swing.JRadioButton BNiveau2;
    private javax.swing.JRadioButton BNiveau3;
    private javax.swing.JTextPane Descriptif;
    private javax.swing.JPanel PCentre;
    private javax.swing.JButton Valider;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
