
import java.awt.Dimension;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gb346159
 */
public class OptionsDlg extends javax.swing.JDialog {

private int choixOpt; // Attribut visant à contenir le choix de l'option de jeu (1 - Quine, 2 - Double Quine, 3 - Carton Plein)
private int nbCol = 5; // // Nombre de colonnes pour nos cartes (= choix dans la JComboBox)
private int nbNum = 5; //  Nombre de numéros pour nos cartes (= nombre inscrit dans le JTextField)
private boolean ok = false;
    public OptionsDlg(java.awt.Frame parent, boolean modal, boolean ca, int nc, int nn) // Informations reçues par la JDialog
    {
        super(parent, modal);
        initComponents();
        setTitle("Options");
        remplirComboCol(); // Méthode qui permet d’initialiser les valeurs de la liste déroulante à 5,6,7,8 et 9.
        // Cocher l’option Quine par défaut - Les boutons doivent être groupés
        BQuine.setSelected(true);
        // Fixer le choix de l’option de jeu à 1
        if (!ca) // test si des cartes ont déjà été achetées
        {    // Fixer le nombre de colonnes à 5 et le nombre de numéros à 5
            NbNumero.setText(""+this.nbNum);
            ComboNbCol.setSelectedIndex(getNbCol()-5);
        }
        else
        {
            this.nbCol=nc;
            this.nbNum=nn;
            NbNumero.setText(""+nn);
            ComboNbCol.setSelectedIndex(getNbCol()-5);
            ComboNbCol.setEnabled(false);
            NbNumero.setEnabled(false);
            Message.setText("Nb de colonnes et de numéros non modifiables");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Annuler = new javax.swing.JButton();
        Valider = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BQuine = new javax.swing.JRadioButton();
        BDoubleQuine = new javax.swing.JRadioButton();
        BCartonPlein = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ComboNbCol = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        NbNumero = new javax.swing.JTextField();
        Message = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Options du jeu");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        Annuler.setText("Annuler");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        jPanel2.add(Annuler);

        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });
        jPanel2.add(Valider);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        jPanel4.setLayout(new java.awt.GridLayout(4, 1));

        jLabel2.setText("Comment voulez-vous jouer ?");
        jPanel4.add(jLabel2);

        buttonGroup1.add(BQuine);
        BQuine.setText("Quine - Une ligne complète");
        jPanel4.add(BQuine);

        buttonGroup1.add(BDoubleQuine);
        BDoubleQuine.setText("Double Quine - Deux lignes complètes");
        jPanel4.add(BDoubleQuine);

        buttonGroup1.add(BCartonPlein);
        BCartonPlein.setText("Carton Plein - Trois lignes complètes");
        jPanel4.add(BCartonPlein);

        jPanel3.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(4, 2));

        jLabel3.setText("Configuration des cartons");
        jPanel5.add(jLabel3);
        jPanel5.add(jLabel4);

        jLabel5.setText("Combien de colonnes ?");
        jPanel5.add(jLabel5);

        ComboNbCol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3" }));
        ComboNbCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboNbColActionPerformed(evt);
            }
        });
        jPanel5.add(ComboNbCol);

        jLabel6.setText("Combien de numéro ?");
        jPanel5.add(jLabel6);

        NbNumero.setText("jTextField1");
        jPanel5.add(NbNumero);
        jPanel5.add(Message);

        jPanel3.add(jPanel5);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboNbColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboNbColActionPerformed

    }//GEN-LAST:event_ComboNbColActionPerformed

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
      this.ok = true;
        if(BQuine.isSelected())
        this.choixOpt = 1;
      else if(BDoubleQuine.isSelected())
          this.choixOpt = 2;
      else if(BCartonPlein.isSelected())
          this.choixOpt = 3;
      this.nbCol = ComboNbCol.getSelectedIndex()+5;
      if(NbNumero.getText()==null)
          System.out.println("Erreur !");
      else
      {
          this.nbNum = Integer.parseInt(NbNumero.getText());
          if(this.nbNum<5||this.nbNum>3*this.nbCol)
              System.out.println("Erreur !");
          else
              this.setVisible(false);
              this.dispose();
      }
    }//GEN-LAST:event_ValiderActionPerformed

    public boolean isOk() {
        return ok;
    }

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
       this.setVisible(false);
       this.dispose();
    }//GEN-LAST:event_AnnulerActionPerformed
    public int getNbCol()
    {
        return this.nbCol;
    }
    public int getChoix()
    {
        return this.choixOpt;
    }
    public int getNbNum()
    {
        return this.nbNum;
    }
    
    private void remplirComboCol()
    {
        ComboNbCol.removeAllItems();
        for(int i=5; i<10; i++)
            ComboNbCol.addItem(""+i);
    }
    
 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionsDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionsDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionsDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionsDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                boolean z = true;
                int a = 5, b = 5;
                OptionsDlg dialog = new OptionsDlg(new javax.swing.JFrame(), true, z, a, b);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JRadioButton BCartonPlein;
    private javax.swing.JRadioButton BDoubleQuine;
    private javax.swing.JRadioButton BQuine;
    private javax.swing.JComboBox<String> ComboNbCol;
    private javax.swing.JLabel Message;
    private javax.swing.JTextField NbNumero;
    private javax.swing.JButton Valider;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
