
import java.awt.Dimension;
import javax.swing.ImageIcon;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gb346159
 */
public class VisuJoueurDlg extends javax.swing.JDialog {

    private Joueur lejoueur;
    private BoutonImage bi;
    
    public VisuJoueurDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        bi = new BoutonImage();
        initComponents();
        jPanel8.add(bi);
        this.setSize(new Dimension(800,500));
        setTitle("Visualisation d'un joueur");
    }
        public VisuJoueurDlg(java.awt.Frame parent, boolean modal, Joueur j) // Constructeur prenant en paramètre un joueur
        {
        super(parent, modal);
        bi = new BoutonImage();
        initComponents();
        jPanel8.add(bi);
        this.setSize(new Dimension(800,500));
        this.lejoueur=j; // Affectation au parametre lejoueur de type Joueur le joueur j passé en argument du constructeur
        initInfos(); // Appelle de la méthode initInfos
        setTitle("Visualisation d'un joueur");
    }

    private void initInfos()
    {
        LPseudo.setText(lejoueur.getPseudo());
        LSolde.setText(""+lejoueur.getSolde());
        PanCouleur.setBackground(lejoueur.getCouleur());
        String msg = "";
        if(lejoueur.getLots().size()==0)
        {
            msg = "Aucun lot gagné";
        }
        else
        {
            for(int i=0; i<lejoueur.getNbLot(); i++)
            {
                msg += ""+lejoueur.getLot(i).toString();
            }
        }
        Edition.setText(msg);
        bi.setImage(lejoueur.getPhoto());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        LPseudo = new javax.swing.JLabel();
        PanCouleur = new javax.swing.JPanel();
        LSolde = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Edition = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Informations relatives à un joueur");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));
        jPanel2.add(jButton1);

        jButton2.setText("Fermer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        jPanel3.setLayout(new java.awt.GridLayout(1, 4));

        jPanel4.setLayout(new java.awt.GridLayout(3, 1));

        jLabel2.setText("Pseudo");
        jPanel4.add(jLabel2);

        jLabel3.setText("Couleur");
        jPanel4.add(jLabel3);

        jLabel4.setText("Solde");
        jPanel4.add(jLabel4);

        jPanel3.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(3, 1));

        LPseudo.setText("jLabel5");
        jPanel5.add(LPseudo);
        jPanel5.add(PanCouleur);

        LSolde.setText("jLabel6");
        jPanel5.add(LSolde);

        jPanel3.add(jPanel5);

        jPanel7.setLayout(new java.awt.GridLayout(1, 1));

        Edition.setColumns(20);
        Edition.setRows(5);
        jScrollPane1.setViewportView(Edition);

        jPanel7.add(jScrollPane1);

        jPanel3.add(jPanel7);

        jPanel8.setLayout(new java.awt.GridLayout(1, 1));
        jPanel3.add(jPanel8);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false); 
        this.dispose();
        // Instructions pour fermer la fenêtre
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VisuJoueurDlg dialog = new VisuJoueurDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Edition;
    private javax.swing.JLabel LPseudo;
    private javax.swing.JLabel LSolde;
    private javax.swing.JPanel PanCouleur;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
